function comparePDs(pdTable1,pdTable2,params,varargin)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% DEFAULT PARAMETERS
move_corr      =  '';
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Some undocumented parameters
if nargin > 1, assignParams(who,params); end % overwrite parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

errorbar(pdTable1.([move_corr 'PD']),pdTable2.([move_corr 'PD']),...
        minusPi2Pi(pdTable2.([move_corr 'PD'])-pdTable2.([move_corr 'PDCI'])(:,1)),...
        minusPi2Pi(pdTable2.([move_corr 'PDCI'])(:,2)-pdTable2.([move_corr 'PD'])),...
        minusPi2Pi(pdTable1.([move_corr 'PD'])-pdTable1.([move_corr 'PDCI'])(:,1)),...
        minusPi2Pi(pdTable1.([move_corr 'PDCI'])(:,2)-pdTable1.([move_corr 'PD'])),...
        varargin{:})
